version: "3.5"
services:
  nodejs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nodejs
    container_name: nodejs
    volumes:
      - ./:/usr/src/app/
    networks:
      - nginx
    ports:
    - 8080:8080
  mysql:
    image: mysql:5.7.8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
    - 3306:3306
    networks:
      - nginx
    volumes:
      - node_mysql_data:/var/lib/mysql


networks:
  nginx:
    driver: bridge
volumes:
  node_mysql_data:
